language: cpp

os:
  - linux
  - osx
  - windows

dist: bionic

env:
  - TARGET_CPU=x64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x64 BUILD_CONFIGURATION=Release

branches:
  only:
    - master
    - develop

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -A $TARGET_CPU || exit 1
  - cmake --build . || exit 1
  - ctest --output-on-failure || exit 1
