language: cpp

os:
  - linux
  - osx
  - windows

dist: bionic

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug TARGET_PLATFORM=x64
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release TARGET_PLATFORM=x64

branches:
  only:
    - master
    - develop

script: |
  mkdir build
  cd build
  if [ "$TRAVIS_OS_NAME" == "windows" ]; then
    cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -A $TARGET_PLATFORM || exit 1
  else
    cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU || exit 1
  fi
  cmake --build . || exit 1
  ctest --output-on-failure || exit 1
