branches:
  only:
    - master
    - develop

language: cpp

arch:
  - amd64

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - clang-9
    update: true
  homebrew:
    packages:
      - gcc
    update: true

script: |
  mkdir build
  cd build
  if [ "$TRAVIS_OS_NAME" == "windows" ]; then
    cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -A $TARGET_PLATFORM || exit 1
  else
    cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU || exit 1
  fi
  cmake --build . || exit 1
  ctest --output-on-failure || exit 1

matrix:
  include:
    # Linux + GCC (Debug)
    - os: linux
      dist: bionic
      env:
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug TARGET_PLATFORM=x64 MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      before_install:
        - eval "${MATRIX_EVAL}"
    # Linux + GCC (Release)
    - os: linux
      dist: bionic
      env:
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release TARGET_PLATFORM=x64 MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      before_install:
        - eval "${MATRIX_EVAL}"
    # Linux + Clang (Debug)
    - os: linux
      dist: bionic
      env:
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug TARGET_PLATFORM=x64 MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
      before_install:
        - eval "${MATRIX_EVAL}"
    # Linux + Clang (Release)
    - os: linux
      dist: bionic
      env:
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release TARGET_PLATFORM=x64 MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
      before_install:
        - eval "${MATRIX_EVAL}"
    # macOS + GCC (Debug)
    - os: osx
      osx_image: xcode11.3
      env:
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug TARGET_PLATFORM=x64 MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      before_install:
        - eval "${MATRIX_EVAL}"
    # macOS + GCC (Release)
    - os: osx
      osx_image: xcode11.3
      env:
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release TARGET_PLATFORM=x64 MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      before_install:
        - eval "${MATRIX_EVAL}"
    # macOS + Clang (Debug)
    - os: osx
      osx_image: xcode11.3
      env:
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug TARGET_PLATFORM=x64
    # macOS + Clang (Release)
    - os: osx
      osx_image: xcode11.3
      env:
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release TARGET_PLATFORM=x64
    # Windows + MSVC (Debug)
    - os: windows
      env:
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug TARGET_PLATFORM=x64
    # Windows + MSVC (Release)
    - os: windows
      env:
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release TARGET_PLATFORM=x64
