version: '{build}'
image: Visual Studio 2019

branches:
  only:
    - master
    - develop

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

before_build:
  - cmd: cd Source/AlgorithmAnalysis
  - cmd: dotnet restore

build:
  verbosity: minimal

test:
  assemblies:
    - '**/*.Tests.dll'

pull_requests:
    do_not_increment_build_number: true

nuget:  
    disable_publish_on_pr: true
