version: '{build}'
image: Visual Studio 2019

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea).
skip_tags: true

shallow_clone: true

# All branches are built by default.

# Build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

before_build:
  - ps: dotnet restore Source/AlgorithmAnalysis

build:
  verbosity: minimal

test:
  assemblies:
    - '**/*.Tests.dll'

pull_requests:
    do_not_increment_build_number: true

nuget:  
    disable_publish_on_pr: true
