version: '{build}'
image: Visual Studio 2019

branches:
  only:
    - master
    - develop

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

install:
  # AppVeyor has WiX installed but it is not on the PATH.
  # We first print out all versions to make it easier to update this if
  # the version changes.
  - dir "c:\Program Files (x86)\WiX Toolset"*
  - set PATH=C:\Program Files (x86)\WiX Toolset v3.11\bin;%PATH%

before_build:
  - cmd: cd Source/AlgorithmAnalysis
  - cmd: dotnet restore

build:
  verbosity: minimal

test:
  assemblies:
    - '**/*.Tests.dll'

pull_requests:
    do_not_increment_build_number: true

nuget:  
    disable_publish_on_pr: true
