//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmAnalysis.DesktopApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DesktopAppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesktopAppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgorithmAnalysis.DesktopApp.Properties.DesktopAppStrings", typeof(DesktopAppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string AlgorithmHint {
            get {
                return ResourceManager.GetString("AlgorithmHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithms parameters.
        /// </summary>
        public static string AlgorithmParametersPanelHeader {
            get {
                return ResourceManager.GetString("AlgorithmParametersPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis parameters.
        /// </summary>
        public static string AnalysisParametersPanelHeader {
            get {
                return ResourceManager.GetString("AnalysisParametersPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis kind for phase one part one.
        /// </summary>
        public static string AnalysisPhaseOnePartOneHint {
            get {
                return ResourceManager.GetString("AnalysisPhaseOnePartOneHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis kind for phase one part two.
        /// </summary>
        public static string AnalysisPhaseOnePartTwoHint {
            get {
                return ResourceManager.GetString("AnalysisPhaseOnePartTwoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis kind for phase two.
        /// </summary>
        public static string AnalysisPhaseTwoHint {
            get {
                return ResourceManager.GetString("AnalysisPhaseTwoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first value of function segment to analyze.
        /// </summary>
        public static string FirstValueHint {
            get {
                return ResourceManager.GetString("FirstValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodness of fit.
        /// </summary>
        public static string GoodnessOfFitHint {
            get {
                return ResourceManager.GetString("GoodnessOfFitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last extrapolation value of function segment to analyze.
        /// </summary>
        public static string LastExtrapolationValueHint {
            get {
                return ResourceManager.GetString("LastExtrapolationValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last value of function segment to analyze.
        /// </summary>
        public static string LastValueHint {
            get {
                return ResourceManager.GetString("LastValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial launches number.
        /// </summary>
        public static string LaunchesNumberHint {
            get {
                return ResourceManager.GetString("LaunchesNumberHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max degree of parallerism.
        /// </summary>
        public static string MaxDegreeOfParallerismText {
            get {
                return ResourceManager.GetString("MaxDegreeOfParallerismText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButtonText {
            get {
                return ResourceManager.GetString("ResetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset analysis parameters.
        /// </summary>
        public static string ResetButtonToolTip {
            get {
                return ResourceManager.GetString("ResetButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string RunButtonText {
            get {
                return ResourceManager.GetString("RunButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run analysis (window will be blocked).
        /// </summary>
        public static string RunButtonToolTip {
            get {
                return ResourceManager.GetString("RunButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of step for function segment.
        /// </summary>
        public static string StepValueHint {
            get {
                return ResourceManager.GetString("StepValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: you cannot specify degree of parallelism
        ///because PC has insufficient number of resources..
        /// </summary>
        public static string WarningInsufficientNumberOfResourcesText {
            get {
                return ResourceManager.GetString("WarningInsufficientNumberOfResourcesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: there are no available algorithms to analyze.
        ///Please, specify at least one algorithm in configuration and restart application..
        /// </summary>
        public static string WarningNoAlgorithmsText {
            get {
                return ResourceManager.GetString("WarningNoAlgorithmsText", resourceCulture);
            }
        }
    }
}
