//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmAnalysis.DesktopApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DesktopAppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesktopAppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgorithmAnalysis.DesktopApp.Properties.DesktopAppStrings", typeof(DesktopAppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced parameters.
        /// </summary>
        public static string AdvancedParametersHeader {
            get {
                return ResourceManager.GetString("AdvancedParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string AlgorithmHint {
            get {
                return ResourceManager.GetString("AlgorithmHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithms parameters.
        /// </summary>
        public static string AlgorithmParametersHeader {
            get {
                return ResourceManager.GetString("AlgorithmParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string AnalysisOptionsHeader {
            get {
                return ResourceManager.GetString("AnalysisOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis parameters.
        /// </summary>
        public static string AnalysisParametersHeader {
            get {
                return ResourceManager.GetString("AnalysisParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis kind for phase one part one.
        /// </summary>
        public static string AnalysisPhaseOnePartOneHint {
            get {
                return ResourceManager.GetString("AnalysisPhaseOnePartOneHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis kind for phase one part two.
        /// </summary>
        public static string AnalysisPhaseOnePartTwoHint {
            get {
                return ResourceManager.GetString("AnalysisPhaseOnePartTwoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis kind for phase two.
        /// </summary>
        public static string AnalysisPhaseTwoHint {
            get {
                return ResourceManager.GetString("AnalysisPhaseTwoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearence.
        /// </summary>
        public static string AppearenceOptionsHeader {
            get {
                return ResourceManager.GetString("AppearenceOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplySettingsButtonText {
            get {
                return ResourceManager.GetString("ApplySettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply all settings.
        /// </summary>
        public static string ApplySettingsButtonToolTip {
            get {
                return ResourceManager.GetString("ApplySettingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell creation mode.
        /// </summary>
        public static string CellCreationModeHint {
            get {
                return ResourceManager.GetString("CellCreationModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseSettingsButtonText {
            get {
                return ResourceManager.GetString("CloseSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close dialog.
        /// </summary>
        public static string CloseSettingsButtonToolTip {
            get {
                return ResourceManager.GetString("CloseSettingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common analysis filename suffix.
        /// </summary>
        public static string CommonAnalysisFilenameSuffixHint {
            get {
                return ResourceManager.GetString("CommonAnalysisFilenameSuffixHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable logging for Excel library.
        /// </summary>
        public static string EnableLogForExcelLibraryText {
            get {
                return ResourceManager.GetString("EnableLogForExcelLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel version.
        /// </summary>
        public static string ExcelVersionHint {
            get {
                return ResourceManager.GetString("ExcelVersionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitButtonText {
            get {
                return ResourceManager.GetString("ExitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close app.
        /// </summary>
        public static string ExitButtonToolTip {
            get {
                return ResourceManager.GetString("ExitButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first value of function segment to analyze.
        /// </summary>
        public static string FirstValueHint {
            get {
                return ResourceManager.GetString("FirstValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodness of fit.
        /// </summary>
        public static string GoodnessOfFitHint {
            get {
                return ResourceManager.GetString("GoodnessOfFitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last extrapolation value of function segment to analyze.
        /// </summary>
        public static string LastExtrapolationValueHint {
            get {
                return ResourceManager.GetString("LastExtrapolationValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last value of function segment to analyze.
        /// </summary>
        public static string LastValueHint {
            get {
                return ResourceManager.GetString("LastValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial launches number.
        /// </summary>
        public static string LaunchesNumberHint {
            get {
                return ResourceManager.GetString("LaunchesNumberHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library provider.
        /// </summary>
        public static string LibraryProviderHint {
            get {
                return ResourceManager.GetString("LibraryProviderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log filename separator.
        /// </summary>
        public static string LogFilenameSeparatorHint {
            get {
                return ResourceManager.GetString("LogFilenameSeparatorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files extension.
        /// </summary>
        public static string LogFilesExtensionHint {
            get {
                return ResourceManager.GetString("LogFilesExtensionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path to store app logs.
        /// </summary>
        public static string LogFolderPathHint {
            get {
                return ResourceManager.GetString("LogFolderPathHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger.
        /// </summary>
        public static string LoggerOptionsHeader {
            get {
                return ResourceManager.GetString("LoggerOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max degree of parallerism.
        /// </summary>
        public static string MaxDegreeOfParallerismText {
            get {
                return ResourceManager.GetString("MaxDegreeOfParallerismText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open analysis results.
        /// </summary>
        public static string OpenAnalysisResultsText {
            get {
                return ResourceManager.GetString("OpenAnalysisResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Excel file path.
        /// </summary>
        public static string OutputExcelFilePathHint {
            get {
                return ResourceManager.GetString("OutputExcelFilePathHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file extension.
        /// </summary>
        public static string OutputFileExtensionHint {
            get {
                return ResourceManager.GetString("OutputFileExtensionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string ReportOptionsHeader {
            get {
                return ResourceManager.GetString("ReportOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetAnalysisButtonText {
            get {
                return ResourceManager.GetString("ResetAnalysisButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset analysis parameters.
        /// </summary>
        public static string ResetAnalysisButtonToolTip {
            get {
                return ResourceManager.GetString("ResetAnalysisButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetSettingButtonText {
            get {
                return ResourceManager.GetString("ResetSettingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings.
        /// </summary>
        public static string ResetSettingButtonToolTip {
            get {
                return ResourceManager.GetString("ResetSettingButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string RunAnalysisButtonText {
            get {
                return ResourceManager.GetString("RunAnalysisButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run analysis (window will be blocked).
        /// </summary>
        public static string RunAnalysisButtonToolTip {
            get {
                return ResourceManager.GetString("RunAnalysisButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open app settings.
        /// </summary>
        public static string SettingsButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show analysis window.
        /// </summary>
        public static string ShowAnalysisWindowText {
            get {
                return ResourceManager.GetString("ShowAnalysisWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string SpecifiedAlgorithmsClickViewText {
            get {
                return ResourceManager.GetString("SpecifiedAlgorithmsClickViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} algorithms..
        /// </summary>
        public static string SpecifiedAlgorithmsManyText {
            get {
                return ResourceManager.GetString("SpecifiedAlgorithmsManyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found any algorithms..
        /// </summary>
        public static string SpecifiedAlgorithmsNotFoundText {
            get {
                return ResourceManager.GetString("SpecifiedAlgorithmsNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} algorithm..
        /// </summary>
        public static string SpecifiedAlgorithmsSingleText {
            get {
                return ResourceManager.GetString("SpecifiedAlgorithmsSingleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of step for function segment.
        /// </summary>
        public static string StepValueHint {
            get {
                return ResourceManager.GetString("StepValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: you cannot specify degree of parallelism.
        ///PC has insufficient number of resources..
        /// </summary>
        public static string WarningInsufficientNumberOfResourcesText {
            get {
                return ResourceManager.GetString("WarningInsufficientNumberOfResourcesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: currently, there are no algorithms
        ///to analyze. Please, specify at least one
        ///algorithm to enable analysis..
        /// </summary>
        public static string WarningNoAlgorithmsInSettingsText {
            get {
                return ResourceManager.GetString("WarningNoAlgorithmsInSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: there are no available algorithms to analyze.
        ///Please, specify at least one algorithm in configuration..
        /// </summary>
        public static string WarningNoAlgorithmsToAnalyseText {
            get {
                return ResourceManager.GetString("WarningNoAlgorithmsToAnalyseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: there are no analysis kind for phase one part one.
        ///Please, check configuration and restart application..
        /// </summary>
        public static string WarningNoAnalysisKindForPhaseOnePartOneText {
            get {
                return ResourceManager.GetString("WarningNoAnalysisKindForPhaseOnePartOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: there are no analysis kind for phase one part two.
        ///Please, check configuration and restart application..
        /// </summary>
        public static string WarningNoAnalysisKindForPhaseOnePartTwoText {
            get {
                return ResourceManager.GetString("WarningNoAnalysisKindForPhaseOnePartTwoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: there are no analysis kind for phase two.
        ///Please, check configuration and restart application..
        /// </summary>
        public static string WarningNoAnalysisKindForPhaseTwoText {
            get {
                return ResourceManager.GetString("WarningNoAnalysisKindForPhaseTwoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: there are no available cell creation mode.
        ///Please, check configuration and restart application..
        /// </summary>
        public static string WarningNoCellCreationModeText {
            get {
                return ResourceManager.GetString("WarningNoCellCreationModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: there are no available Excel versions.
        ///Please, check configuration and restart application..
        /// </summary>
        public static string WarningNoExcelVersionText {
            get {
                return ResourceManager.GetString("WarningNoExcelVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: there are no goodness of fit methods.
        ///Please, check configuration and restart application..
        /// </summary>
        public static string WarningNoGoodnessOfFitMethodsText {
            get {
                return ResourceManager.GetString("WarningNoGoodnessOfFitMethodsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: there are no available library providers.
        ///Please, check configuration and restart application..
        /// </summary>
        public static string WarningNoLibraryProviderText {
            get {
                return ResourceManager.GetString("WarningNoLibraryProviderText", resourceCulture);
            }
        }
    }
}
