//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmAnalysis.DomainLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelStringsPhaseOnePartTwo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelStringsPhaseOnePartTwo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgorithmAnalysis.DomainLogic.Properties.ExcelStringsPhaseOnePartTwo", typeof(ExcelStringsPhaseOnePartTwo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные параметры.
        /// </summary>
        internal static string AdditionalParametersColumnName {
            get {
                return ResourceManager.GetString("AdditionalParametersColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значения.
        /// </summary>
        internal static string AdditionalParametersValuesColumnName {
            get {
                return ResourceManager.GetString("AdditionalParametersValuesColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альфа.
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average f(n).
        /// </summary>
        internal static string AverageFunc {
            get {
                return ResourceManager.GetString("AverageFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бета.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решение на основе бета распределения.
        /// </summary>
        internal static string BetaDistributionSolutionColumnName {
            get {
                return ResourceManager.GetString("BetaDistributionSolutionColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка гитотезы функцией ТЕСТ.
        /// </summary>
        internal static string CheckTestFucntion {
            get {
                return ResourceManager.GetString("CheckTestFucntion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Критическое значение χ2.
        /// </summary>
        internal static string Chi2Critical {
            get {
                return ResourceManager.GetString("Chi2Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to χ2 наблюдаемое.
        /// </summary>
        internal static string Chi2Observable {
            get {
                return ResourceManager.GetString("Chi2Observable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение для χ2.
        /// </summary>
        internal static string Chi2ValueColumnName {
            get {
                return ResourceManager.GetString("Chi2ValueColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициент доверия.
        /// </summary>
        internal static string ConfidenceFactor {
            get {
                return ResourceManager.GetString("ConfidenceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.95.
        /// </summary>
        internal static string ConfidenceFactorValue {
            get {
                return ResourceManager.GetString("ConfidenceFactorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эмперические частоты.
        /// </summary>
        internal static string EmpiricalFrequencyColumnName {
            get {
                return ResourceManager.GetString("EmpiricalFrequencyColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eps.
        /// </summary>
        internal static string Epsilon {
            get {
                return ResourceManager.GetString("Epsilon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.001.
        /// </summary>
        internal static string EpsilonValue {
            get {
                return ResourceManager.GetString("EpsilonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во экспериментов.
        /// </summary>
        internal static string ExperimentsNumber {
            get {
                return ResourceManager.GetString("ExperimentsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во степеней свободы.
        /// </summary>
        internal static string FreedomDegreesNumber {
            get {
                return ResourceManager.GetString("FreedomDegreesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота.
        /// </summary>
        internal static string FrequencyColumnName {
            get {
                return ResourceManager.GetString("FrequencyColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число полусегментов для гистограммы.
        /// </summary>
        internal static string HistogramSemisegmentsNumber {
            get {
                return ResourceManager.GetString("HistogramSemisegmentsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер входа.
        /// </summary>
        internal static string InputDataSize {
            get {
                return ResourceManager.GetString("InputDataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина интервала.
        /// </summary>
        internal static string IntervalLength {
            get {
                return ResourceManager.GetString("IntervalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max f(n).
        /// </summary>
        internal static string MaxFunc {
            get {
                return ResourceManager.GetString("MaxFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное значение выборки.
        /// </summary>
        internal static string MaximumValue {
            get {
                return ResourceManager.GetString("MaximumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min f(n).
        /// </summary>
        internal static string MinFunc {
            get {
                return ResourceManager.GetString("MinFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальное значение выборки.
        /// </summary>
        internal static string MinimumValue {
            get {
                return ResourceManager.GetString("MinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решение на основе нормального распределения.
        /// </summary>
        internal static string NormalDistributionSolutionColumnName {
            get {
                return ResourceManager.GetString("NormalDistributionSolutionColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированные значения.
        /// </summary>
        internal static string NormalizedColumnName {
            get {
                return ResourceManager.GetString("NormalizedColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированное среднее.
        /// </summary>
        internal static string NormalizedMean {
            get {
                return ResourceManager.GetString("NormalizedMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированная дисперсия.
        /// </summary>
        internal static string NormalizedVarience {
            get {
                return ResourceManager.GetString("NormalizedVarience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во операций.
        /// </summary>
        internal static string OperationColumnName {
            get {
                return ResourceManager.GetString("OperationColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ещё.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карман.
        /// </summary>
        internal static string PocketColumnName {
            get {
                return ResourceManager.GetString("PocketColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный объём выборки.
        /// </summary>
        internal static string PreliminarySampleSize {
            get {
                return ResourceManager.GetString("PreliminarySampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочное отклонение.
        /// </summary>
        internal static string SampleDeviation {
            get {
                return ResourceManager.GetString("SampleDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочное среднее.
        /// </summary>
        internal static string SampleMean {
            get {
                return ResourceManager.GetString("SampleMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочная дисперсия.
        /// </summary>
        internal static string SampleVariance {
            get {
                return ResourceManager.GetString("SampleVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень значимости.
        /// </summary>
        internal static string SignificanceLevel {
            get {
                return ResourceManager.GetString("SignificanceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - {0}.
        /// </summary>
        internal static string SignificanceLevelFormula {
            get {
                return ResourceManager.GetString("SignificanceLevelFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размах.
        /// </summary>
        internal static string Span {
            get {
                return ResourceManager.GetString("Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теоретические частоты.
        /// </summary>
        internal static string TheoreticalFrequencyColumnName {
            get {
                return ResourceManager.GetString("TheoreticalFrequencyColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теоретический максимум.
        /// </summary>
        internal static string TheoreticalMax {
            get {
                return ResourceManager.GetString("TheoreticalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теоретический минимум.
        /// </summary>
        internal static string TheoreticalMin {
            get {
                return ResourceManager.GetString("TheoreticalMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициент вариации.
        /// </summary>
        internal static string VariationCoefficient {
            get {
                return ResourceManager.GetString("VariationCoefficient", resourceCulture);
            }
        }
    }
}
