//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmAnalysis.DomainLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelStringsPhaseTwo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelStringsPhaseTwo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgorithmAnalysis.DomainLogic.Properties.ExcelStringsPhaseTwo", typeof(ExcelStringsPhaseTwo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные данные.
        /// </summary>
        internal static string AdditionalData {
            get {
                return ResourceManager.GetString("AdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альфа.
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to α(n).
        /// </summary>
        internal static string AlphaN {
            get {
                return ResourceManager.GetString("AlphaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бета.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to β(n).
        /// </summary>
        internal static string BetaN {
            get {
                return ResourceManager.GetString("BetaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сравнение.
        /// </summary>
        internal static string Comparison {
            get {
                return ResourceManager.GetString("Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fγ(n).
        /// </summary>
        internal static string ComplexityFunction {
            get {
                return ResourceManager.GetString("ComplexityFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.95.
        /// </summary>
        internal static string ConfidenceFactorValue {
            get {
                return ResourceManager.GetString("ConfidenceFactorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xγ(n).
        /// </summary>
        internal static string LeftYQuantile {
            get {
                return ResourceManager.GetString("LeftYQuantile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string NColumnName {
            get {
                return ResourceManager.GetString("NColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированное среднее.
        /// </summary>
        internal static string NormalizedMean {
            get {
                return ResourceManager.GetString("NormalizedMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированная дисперсия.
        /// </summary>
        internal static string NormalizedVarience {
            get {
                return ResourceManager.GetString("NormalizedVarience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочное отклонение.
        /// </summary>
        internal static string SampleDeviation {
            get {
                return ResourceManager.GetString("SampleDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочное среднее.
        /// </summary>
        internal static string SampleMean {
            get {
                return ResourceManager.GetString("SampleMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объём выборки, n.
        /// </summary>
        internal static string SampleSize {
            get {
                return ResourceManager.GetString("SampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочная дисперсия.
        /// </summary>
        internal static string SampleVariance {
            get {
                return ResourceManager.GetString("SampleVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - {0}.
        /// </summary>
        internal static string SignificanceLevelFormula {
            get {
                return ResourceManager.GetString("SignificanceLevelFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теоретическое значение в среднем.
        /// </summary>
        internal static string TheoreticalAverage {
            get {
                return ResourceManager.GetString("TheoreticalAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теоретический максимум.
        /// </summary>
        internal static string TheoreticalMax {
            get {
                return ResourceManager.GetString("TheoreticalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теоретический минимум.
        /// </summary>
        internal static string TheoreticalMin {
            get {
                return ResourceManager.GetString("TheoreticalMin", resourceCulture);
            }
        }
    }
}
