//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmAnalysis.DomainLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelStringsPhaseTwo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelStringsPhaseTwo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgorithmAnalysis.DomainLogic.Properties.ExcelStringsPhaseTwo", typeof(ExcelStringsPhaseTwo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные данные.
        /// </summary>
        internal static string AdditionalDataColumnName {
            get {
                return ResourceManager.GetString("AdditionalDataColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альфа.
        /// </summary>
        internal static string AlphaColumnName {
            get {
                return ResourceManager.GetString("AlphaColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to α(n).
        /// </summary>
        internal static string AlphaNColumnName {
            get {
                return ResourceManager.GetString("AlphaNColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значения анализа.
        /// </summary>
        internal static string AnalysisValuesColumnName {
            get {
                return ResourceManager.GetString("AnalysisValuesColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бета.
        /// </summary>
        internal static string BetaColumnName {
            get {
                return ResourceManager.GetString("BetaColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to β(n).
        /// </summary>
        internal static string BetaNColumnName {
            get {
                return ResourceManager.GetString("BetaNColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сравнение (max / fγ(n)).
        /// </summary>
        internal static string ComparisonColumnName {
            get {
                return ResourceManager.GetString("ComparisonColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fγ(n).
        /// </summary>
        internal static string ComplexityFunctionColumnName {
            get {
                return ResourceManager.GetString("ComplexityFunctionColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.95.
        /// </summary>
        internal static string ConfidenceFactorValue {
            get {
                return ResourceManager.GetString("ConfidenceFactorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xγ(n).
        /// </summary>
        internal static string LeftYQuantileColumnName {
            get {
                return ResourceManager.GetString("LeftYQuantileColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string NColumnName {
            get {
                return ResourceManager.GetString("NColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированное среднее.
        /// </summary>
        internal static string NormalizedMeanColumnName {
            get {
                return ResourceManager.GetString("NormalizedMeanColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированное среднее.
        /// </summary>
        internal static string NormalizedNMeanColumnName {
            get {
                return ResourceManager.GetString("NormalizedNMeanColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированная дисперсия.
        /// </summary>
        internal static string NormalizedNVarianceColumnName {
            get {
                return ResourceManager.GetString("NormalizedNVarianceColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированная дисперсия.
        /// </summary>
        internal static string NormalizedVarianceColumnName {
            get {
                return ResourceManager.GetString("NormalizedVarianceColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочное отклонение.
        /// </summary>
        internal static string SampleDeviationColumnName {
            get {
                return ResourceManager.GetString("SampleDeviationColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочное среднее.
        /// </summary>
        internal static string SampleMeanColumnName {
            get {
                return ResourceManager.GetString("SampleMeanColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объём выборки, n.
        /// </summary>
        internal static string SampleSizeColumnName {
            get {
                return ResourceManager.GetString("SampleSizeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочная дисперсия.
        /// </summary>
        internal static string SampleVarianceColumnName {
            get {
                return ResourceManager.GetString("SampleVarianceColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - {0}.
        /// </summary>
        internal static string SignificanceLevelFormula {
            get {
                return ResourceManager.GetString("SignificanceLevelFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теоретическое значение в среднем.
        /// </summary>
        internal static string TheoreticalAverageColumnName {
            get {
                return ResourceManager.GetString("TheoreticalAverageColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теоретический максимум.
        /// </summary>
        internal static string TheoreticalMaxColumnName {
            get {
                return ResourceManager.GetString("TheoreticalMaxColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теоретический минимум.
        /// </summary>
        internal static string TheoreticalMinColumnName {
            get {
                return ResourceManager.GetString("TheoreticalMinColumnName", resourceCulture);
            }
        }
    }
}
