//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmAnalysis.DomainLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelStringsPhaseOnePartOne {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelStringsPhaseOnePartOne() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgorithmAnalysis.DomainLogic.Properties.ExcelStringsPhaseOnePartOne", typeof(ExcelStringsPhaseOnePartOne).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные параметры.
        /// </summary>
        internal static string AdditionalParametersColumnName {
            get {
                return ResourceManager.GetString("AdditionalParametersColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значения.
        /// </summary>
        internal static string AdditionalParametersValuesColumnName {
            get {
                return ResourceManager.GetString("AdditionalParametersValuesColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альфа.
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average f(n).
        /// </summary>
        internal static string AverageFunc {
            get {
                return ResourceManager.GetString("AverageFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бета.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решение на основе бета распределения.
        /// </summary>
        internal static string BetaDistributionSolutionColumnName {
            get {
                return ResourceManager.GetString("BetaDistributionSolutionColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассчитанный объём выборки.
        /// </summary>
        internal static string CalculatedSampleSize {
            get {
                return ResourceManager.GetString("CalculatedSampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициент доверия.
        /// </summary>
        internal static string ConfidenceFactor {
            get {
                return ResourceManager.GetString("ConfidenceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.95.
        /// </summary>
        internal static string ConfidenceFactorValue {
            get {
                return ResourceManager.GetString("ConfidenceFactorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дельта для eps=0,001.
        /// </summary>
        internal static string DeltaForEpsilon {
            get {
                return ResourceManager.GetString("DeltaForEpsilon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eps.
        /// </summary>
        internal static string Epsilon {
            get {
                return ResourceManager.GetString("Epsilon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.001.
        /// </summary>
        internal static string EpsilonValue {
            get {
                return ResourceManager.GetString("EpsilonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во экспериментов.
        /// </summary>
        internal static string ExperimentsNumber {
            get {
                return ResourceManager.GetString("ExperimentsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер входа.
        /// </summary>
        internal static string InputDataSize {
            get {
                return ResourceManager.GetString("InputDataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижний предел интегрирования.
        /// </summary>
        internal static string LowerIntegrationBound {
            get {
                return ResourceManager.GetString("LowerIntegrationBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max f(n).
        /// </summary>
        internal static string MaxFunc {
            get {
                return ResourceManager.GetString("MaxFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min f(n).
        /// </summary>
        internal static string MinFunc {
            get {
                return ResourceManager.GetString("MinFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решение на основе нормального распределения.
        /// </summary>
        internal static string NormalDistributionSolutionColumnName {
            get {
                return ResourceManager.GetString("NormalDistributionSolutionColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированные значения.
        /// </summary>
        internal static string NormalizedColumnName {
            get {
                return ResourceManager.GetString("NormalizedColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированное дельта.
        /// </summary>
        internal static string NormalizedDelta {
            get {
                return ResourceManager.GetString("NormalizedDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированное среднее.
        /// </summary>
        internal static string NormalizedMean {
            get {
                return ResourceManager.GetString("NormalizedMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированная дисперсия.
        /// </summary>
        internal static string NormalizedVarience {
            get {
                return ResourceManager.GetString("NormalizedVarience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во операций.
        /// </summary>
        internal static string OperationColumnName {
            get {
                return ResourceManager.GetString("OperationColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение P(n).
        /// </summary>
        internal static string PFunc {
            get {
                return ResourceManager.GetString("PFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный объём выборки.
        /// </summary>
        internal static string PreliminarySampleSize {
            get {
                return ResourceManager.GetString("PreliminarySampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочное отклонение.
        /// </summary>
        internal static string SampleDeviation {
            get {
                return ResourceManager.GetString("SampleDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочное среднее.
        /// </summary>
        internal static string SampleMean {
            get {
                return ResourceManager.GetString("SampleMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочная дисперсия.
        /// </summary>
        internal static string SampleVariance {
            get {
                return ResourceManager.GetString("SampleVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень значимости.
        /// </summary>
        internal static string SignificanceLevel {
            get {
                return ResourceManager.GetString("SignificanceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - {0}.
        /// </summary>
        internal static string SignificanceLevelFormula {
            get {
                return ResourceManager.GetString("SignificanceLevelFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размах.
        /// </summary>
        internal static string Span {
            get {
                return ResourceManager.GetString("Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теоретический максимум.
        /// </summary>
        internal static string TheoreticalMax {
            get {
                return ResourceManager.GetString("TheoreticalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теоретический минимум.
        /// </summary>
        internal static string TheoreticalMin {
            get {
                return ResourceManager.GetString("TheoreticalMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u(n).
        /// </summary>
        internal static string UFunc {
            get {
                return ResourceManager.GetString("UFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхний предел интегрирования.
        /// </summary>
        internal static string UpperIntegrationBound {
            get {
                return ResourceManager.GetString("UpperIntegrationBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициент вариации.
        /// </summary>
        internal static string VariationCoefficient {
            get {
                return ResourceManager.GetString("VariationCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v(n).
        /// </summary>
        internal static string VFunc {
            get {
                return ResourceManager.GetString("VFunc", resourceCulture);
            }
        }
    }
}
