//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmAnalysis.DomainLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgorithmAnalysis.DomainLogic.Properties.ExcelStrings", typeof(ExcelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные параметры.
        /// </summary>
        internal static string AdditionalParametersColumnName {
            get {
                return ResourceManager.GetString("AdditionalParametersColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значения.
        /// </summary>
        internal static string AdditionalParametersValuesColumnName {
            get {
                return ResourceManager.GetString("AdditionalParametersValuesColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average f(n).
        /// </summary>
        internal static string AverageFunc {
            get {
                return ResourceManager.GetString("AverageFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average f(n).
        /// </summary>
        internal static string AverageFuncFormula {
            get {
                return ResourceManager.GetString("AverageFuncFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассчитанный объём выборки.
        /// </summary>
        internal static string CalculatedSampleSize {
            get {
                return ResourceManager.GetString("CalculatedSampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициент доверия.
        /// </summary>
        internal static string ConfidenceFactor {
            get {
                return ResourceManager.GetString("ConfidenceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.95.
        /// </summary>
        internal static string ConfidenceFactorValue {
            get {
                return ResourceManager.GetString("ConfidenceFactorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eps.
        /// </summary>
        internal static string Epsilon {
            get {
                return ResourceManager.GetString("Epsilon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.001.
        /// </summary>
        internal static string EpsilonValue {
            get {
                return ResourceManager.GetString("EpsilonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во экспериментов.
        /// </summary>
        internal static string ExperimentsNumber {
            get {
                return ResourceManager.GetString("ExperimentsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер входа.
        /// </summary>
        internal static string InputDataSize {
            get {
                return ResourceManager.GetString("InputDataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max f(n).
        /// </summary>
        internal static string MaxFunc {
            get {
                return ResourceManager.GetString("MaxFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max f(n).
        /// </summary>
        internal static string MaxFuncFormula {
            get {
                return ResourceManager.GetString("MaxFuncFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min f(n).
        /// </summary>
        internal static string MinFunc {
            get {
                return ResourceManager.GetString("MinFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min f(n).
        /// </summary>
        internal static string MinFuncFormula {
            get {
                return ResourceManager.GetString("MinFuncFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решение на основе нормального распределения.
        /// </summary>
        internal static string NormalDistributionSolutionColumnName {
            get {
                return ResourceManager.GetString("NormalDistributionSolutionColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормированные значения.
        /// </summary>
        internal static string NormalizedColumnName {
            get {
                return ResourceManager.GetString("NormalizedColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во операций.
        /// </summary>
        internal static string OperationColumnName {
            get {
                return ResourceManager.GetString("OperationColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный объём выборки.
        /// </summary>
        internal static string PreliminarySampleSize {
            get {
                return ResourceManager.GetString("PreliminarySampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочное отклонение.
        /// </summary>
        internal static string SampleDeviation {
            get {
                return ResourceManager.GetString("SampleDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочное среднее.
        /// </summary>
        internal static string SampleMean {
            get {
                return ResourceManager.GetString("SampleMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборочная дисперсия.
        /// </summary>
        internal static string SampleVariance {
            get {
                return ResourceManager.GetString("SampleVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень значимости.
        /// </summary>
        internal static string SignificanceLevel {
            get {
                return ResourceManager.GetString("SignificanceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - $F$7.
        /// </summary>
        internal static string SignificanceLevelFormula {
            get {
                return ResourceManager.GetString("SignificanceLevelFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициент вариации.
        /// </summary>
        internal static string VariationCoefficient {
            get {
                return ResourceManager.GetString("VariationCoefficient", resourceCulture);
            }
        }
    }
}
